name: CI
permissions:
  contents: none

# Run this workflow every time a commit is pushed to main
# The `workflow_dispatch` had been added to be able to run the
# workflow manually (for testing purposes).
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    build:
        name: Trigger "Deploy schemas (s-aks)" pipeline on Azure DevOps.
        runs-on: ubuntu-latest
        steps:
        - name: Call Azure
          uses: amsterdam/trigger-ado-pipeline@v1.1
          with:
            pipeline-id: 5132
            organisation: CloudCompetenceCenter
            project: 'Data Diensten'
            pat-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
